language: python
python:
- 3.9.0
install:
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- python -m unittest
deploy:
  provider: heroku
  app: egc-bailon-bot-slack
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN